import Anthropic from '@anthropic-ai/sdk'
import type { TriviaCategory, TriviaQuestion } from '@/types'

/** Game types whose question/prompt pool can be generated by AI. */
export type AiQuestionGameType =
  | 'would_you_rather'
  | 'this_or_that'
  | 'most_likely_to'
  | 'never_have_i_ever'
  | 'pick_a_number'
  | 'trivia'
  | 'codewords'
  | 'describe_it'

export const AI_QUESTION_GAME_TYPES: AiQuestionGameType[] = [
  'would_you_rather',
  'this_or_that',
  'most_likely_to',
  'never_have_i_ever',
  'pick_a_number',
  'trivia',
  'codewords',
  'describe_it',
]

export interface GenerateAiQuestionsParams {
  gameType: AiQuestionGameType
  count: number
  theme?: string
  customPrompt?: string
  /** Default trivia category for generated questions. Ignored by non-trivia games. */
  triviaCategory?: TriviaCategory
  apiKey: string
}

/** A pair-choice question ({ optionA, optionB }) — used by Would You Rather and This or That. */
type PairQuestion = { optionA: string; optionB: string }

/**
 * Generated questions, in the same storage shape the CSV/manual importers produce for each game,
 * so the result drops straight into `custom_questions` with `question_source: 'custom'`.
 */
export type AiQuestionsResult =
  | { gameType: 'would_you_rather' | 'this_or_that'; questions: PairQuestion[] }
  | {
      gameType: 'most_likely_to' | 'never_have_i_ever' | 'pick_a_number' | 'codewords' | 'describe_it'
      questions: string[]
    }
  | { gameType: 'trivia'; questions: TriviaQuestion[] }

const SYSTEM_PROMPT = `You are a party game content generator. Generate fun, creative, and socially engaging content for a group of friends playing a party game. Keep it playful and entertaining — not offensive, not sexual, not controversial, and safe for a mixed group. Return ONLY valid JSON, no markdown fences or extra text.`

function themeLines(params: GenerateAiQuestionsParams): string[] {
  return [
    params.theme ? `Theme/setting: ${params.theme}` : '',
    params.customPrompt ? `Additional context: ${params.customPrompt}` : '',
  ]
}

function buildUserPrompt(params: GenerateAiQuestionsParams): string {
  const { gameType, count } = params
  const t = themeLines(params)

  switch (gameType) {
    case 'would_you_rather':
      return [
        `Generate ${count} "Would You Rather" questions for a party game.`,
        ``,
        ...t,
        ``,
        `Rules:`,
        `- Each question has two options (optionA and optionB)`,
        `- Make questions fun, creative, and conversation-starting`,
        `- Avoid anything offensive, sexual, or controversial`,
        `- Vary the difficulty and absurdity levels`,
        ``,
        `Return a JSON array of objects with "optionA" and "optionB" string fields.`,
        `Example: [{"optionA": "Never eat pizza again", "optionB": "Never eat ice cream again"}]`,
      ]
        .filter(Boolean)
        .join('\n')

    case 'this_or_that':
      return [
        `Generate ${count} "This or That" choices for a party game.`,
        ``,
        ...t,
        ``,
        `Rules:`,
        `- Each item is a simple either/or pair (optionA and optionB), e.g. "Coffee" vs "Tea"`,
        `- Keep both options short (1-4 words)`,
        `- Make them fun and debatable`,
        `- Avoid anything offensive, sexual, or controversial`,
        ``,
        `Return a JSON array of objects with "optionA" and "optionB" string fields.`,
        `Example: [{"optionA": "Coffee", "optionB": "Tea"}, {"optionA": "Beach", "optionB": "Mountains"}]`,
      ]
        .filter(Boolean)
        .join('\n')

    case 'most_likely_to':
      return [
        `Generate ${count} "Most Likely To" prompts for a party game.`,
        ``,
        ...t,
        ``,
        `Rules:`,
        `- Each prompt completes "Who is most likely to..."`,
        `- Make prompts fun, creative, and conversation-starting`,
        `- Avoid anything offensive, sexual, or controversial`,
        `- Vary the seriousness and absurdity levels`,
        ``,
        `Return a JSON array of strings. Do NOT include the "Who is most likely to" prefix.`,
        `Example: ["fall asleep during a movie", "become famous on social media"]`,
      ]
        .filter(Boolean)
        .join('\n')

    case 'never_have_i_ever':
      return [
        `Generate ${count} "Never Have I Ever" statements for a party game.`,
        ``,
        ...t,
        ``,
        `Rules:`,
        `- Each statement completes "Never have I ever..."`,
        `- Make statements fun, revealing, and conversation-starting`,
        `- Avoid anything offensive, sexual, or controversial`,
        `- Mix mundane and surprising statements`,
        ``,
        `Return a JSON array of strings. Do NOT include the "Never have I ever" prefix.`,
        `Example: ["eaten an entire pizza by myself", "pretended to know a song everyone else knew"]`,
      ]
        .filter(Boolean)
        .join('\n')

    case 'pick_a_number':
      return [
        `Generate ${count} open-ended personal questions for a "Pick a Number" party game,`,
        `where a player lands on a numbered question and answers it out loud to the group.`,
        ``,
        ...t,
        ``,
        `Rules:`,
        `- Each is a single revealing or funny question (e.g. "What's the most embarrassing thing in your search history?")`,
        `- Make them conversation-starting and a little daring, but safe for a mixed group`,
        `- Avoid anything offensive, sexual, or controversial`,
        ``,
        `Return a JSON array of strings, one question each.`,
        `Example: ["What's your most controversial food opinion?", "Who was your first crush?"]`,
      ]
        .filter(Boolean)
        .join('\n')

    case 'trivia':
      return [
        `Generate ${count} multiple-choice trivia questions for a party game.`,
        ``,
        ...t,
        ``,
        `Rules:`,
        `- Each question has exactly 4 answer choices`,
        `- Exactly one choice is correct; "correctIndex" is its 0-based position`,
        `- Keep questions factual and unambiguous`,
        `- Vary the difficulty`,
        ``,
        `Return a JSON array of objects with "question" (string), "choices" (array of exactly 4 strings),`,
        `and "correctIndex" (integer 0-3).`,
        `Example: [{"question": "What is the capital of France?", "choices": ["Paris", "Lyon", "Nice", "Marseille"], "correctIndex": 0}]`,
      ]
        .filter(Boolean)
        .join('\n')

    case 'codewords':
      return [
        `Generate ${count} single words for a "Codewords" board game (like Codenames).`,
        ``,
        ...t,
        ``,
        `Rules:`,
        `- Each entry is ONE word (no spaces, no phrases)`,
        `- Prefer common, guessable nouns`,
        `- Avoid anything offensive or controversial`,
        ``,
        `Return a JSON array of single-word strings.`,
        `Example: ["river", "robot", "castle", "guitar"]`,
      ]
        .filter(Boolean)
        .join('\n')

    case 'describe_it':
      return [
        `Generate ${count} words or short phrases for a "Describe It" / charades-style party game,`,
        `where one player describes the word for teammates to guess.`,
        ``,
        ...t,
        ``,
        `Rules:`,
        `- Each entry is a word or very short phrase (1-3 words)`,
        `- Mix easy and hard items`,
        `- Avoid anything offensive or controversial`,
        ``,
        `Return a JSON array of strings.`,
        `Example: ["pineapple", "roller coaster", "Eiffel Tower", "yawning"]`,
      ]
        .filter(Boolean)
        .join('\n')
  }
}

function extractJson(text: string): string {
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/)
  if (fenced) return fenced[1].trim()
  const bracketStart = text.indexOf('[')
  if (bracketStart !== -1) {
    const bracketEnd = text.lastIndexOf(']')
    if (bracketEnd > bracketStart) return text.slice(bracketStart, bracketEnd + 1)
    return text.slice(bracketStart)
  }
  return text
}

function parsePairResponse(raw: string): PairQuestion[] {
  const parsed = JSON.parse(raw)
  if (!Array.isArray(parsed)) throw new Error('Expected JSON array')
  return parsed.map((item: unknown, i: number) => {
    const obj = item as Record<string, unknown>
    if (
      typeof item !== 'object' ||
      item === null ||
      typeof obj.optionA !== 'string' ||
      typeof obj.optionB !== 'string'
    ) {
      throw new Error(`Invalid pair question at index ${i}`)
    }
    const optionA = obj.optionA.trim()
    const optionB = obj.optionB.trim()
    if (!optionA || !optionB) throw new Error(`Empty option at index ${i}`)
    return { optionA, optionB }
  })
}

function parseStringArrayResponse(raw: string): string[] {
  const parsed = JSON.parse(raw)
  if (!Array.isArray(parsed)) throw new Error('Expected JSON array')
  return parsed.map((item: unknown, i: number) => {
    if (typeof item !== 'string') throw new Error(`Expected string at index ${i}`)
    const v = item.trim()
    if (!v) throw new Error(`Empty entry at index ${i}`)
    return v
  })
}

function parseWordArrayResponse(raw: string): string[] {
  // Codewords entries must be single words — reject anything with whitespace rather than
  // silently truncating it to the first token.
  return parseStringArrayResponse(raw).map((w, i) => {
    if (/\s/.test(w)) throw new Error(`Codeword at index ${i} must be a single word`)
    return w
  })
}

function parseTriviaResponse(raw: string, category: TriviaCategory): TriviaQuestion[] {
  const parsed = JSON.parse(raw)
  if (!Array.isArray(parsed)) throw new Error('Expected JSON array')
  return parsed.map((item: unknown, i: number) => {
    const obj = item as Record<string, unknown>
    if (typeof item !== 'object' || item === null || typeof obj.question !== 'string' || !Array.isArray(obj.choices)) {
      throw new Error(`Invalid trivia question at index ${i}`)
    }
    const question = obj.question.trim()
    if (!question) throw new Error(`Empty trivia question at index ${i}`)

    const rawChoices = obj.choices
    if (rawChoices.length !== 4 || !rawChoices.every((c): c is string => typeof c === 'string')) {
      throw new Error(`Trivia question at index ${i} needs exactly 4 string choices`)
    }
    const choices = rawChoices.map((c) => c.trim())
    if (choices.some((c) => !c)) throw new Error(`Empty trivia choice at index ${i}`)

    const correctIndex = Number(obj.correctIndex)
    if (!Number.isInteger(correctIndex) || correctIndex < 0 || correctIndex >= choices.length) {
      throw new Error(`Invalid correctIndex at index ${i}`)
    }
    return { question, choices, correctIndex, category }
  })
}

export async function generateAiQuestions(params: GenerateAiQuestionsParams): Promise<AiQuestionsResult> {
  const apiKey = params.apiKey
  if (!apiKey) throw new Error('A Claude API key is required to generate questions')

  const client = new Anthropic({ apiKey, timeout: 30_000 })

  const response = await client.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 4096,
    system: SYSTEM_PROMPT,
    messages: [{ role: 'user', content: buildUserPrompt(params) }],
  })

  const textBlock = response.content.find((block) => block.type === 'text')
  if (!textBlock || textBlock.type !== 'text') throw new Error('No text response from Claude')

  const jsonStr = extractJson(textBlock.text)

  switch (params.gameType) {
    case 'would_you_rather':
    case 'this_or_that':
      return { gameType: params.gameType, questions: parsePairResponse(jsonStr) }
    case 'most_likely_to':
    case 'never_have_i_ever':
    case 'pick_a_number':
    case 'describe_it':
      return { gameType: params.gameType, questions: parseStringArrayResponse(jsonStr) }
    case 'codewords':
      return { gameType: 'codewords', questions: parseWordArrayResponse(jsonStr) }
    case 'trivia':
      return { gameType: 'trivia', questions: parseTriviaResponse(jsonStr, params.triviaCategory ?? 'general') }
  }
}
