/** Built-in Most Likely To prompts — 80 questions (party / spicy tone) */

import { pickLeastUsed } from '@/lib/question-picker'

export const MLT_QUESTIONS: string[] = [
  'Who is most likely to hook up with someone from this friend group?',
  'Who is most likely to send a booty call text to the wrong group chat?',
  'Who is most likely to have the highest body count?',
  'Who is most likely to fake an orgasm convincingly?',
  'Who is most likely to say the wrong name during sex?',
  'Who is most likely to get back with their toxic ex after breakup sex?',
  'Who is most likely to hook up on the first hangout?',
  'Who is most likely to catch feelings from a one-night stand?',
  'Who is most likely to ghost someone after amazing sex?',
  'Who is most likely to stay after terrible sex out of guilt?',
  'Who is most likely to have a walk of shame story for the ages?',
  'Who is most likely to leave before the sun comes up?',
  'Who is most likely to moan loud enough for the neighbors to complain?',
  'Who is most likely to hook up in a bathroom at a wedding?',
  'Who is most likely to get caught having sex somewhere public?',
  'Who is most likely to have sex in a car?',
  'Who is most likely to hook up with a coworker?',
  'Who is most likely to flirt their way out of a speeding ticket?',
  'Who is most likely to send nudes to the wrong person?',
  'Who is most likely to have a secret folder of thirst traps?',
  'Who is most likely to slide into DMs at 2am?',
  'Who is most likely to double-text after getting left on read?',
  "Who is most likely to stalk an ex's new partner on Instagram?",
  "Who is most likely to still have their ex's nudes saved?",
  "Who is most likely to hook up with a friend's ex?",
  'Who is most likely to lie about their body count?',
  'Who is most likely to have a situationship that never ends?',
  'Who is most likely to catch feelings for a sneaky link?',
  'Who is most likely to have someone saved in their phone under a fake name?',
  'Who is most likely to use a dating app while in a relationship?',
  "Who is most likely to match with someone they know and pretend it's an accident?",
  'Who is most likely to hook up with someone they met the same night?',
  'Who is most likely to make the first move at the club?',
  'Who is most likely to go home with the bartender?',
  'Who is most likely to have a one-night stand on vacation and never learn their last name?',
  'Who is most likely to be down for a threesome if you asked tonight?',
  'Who is most likely to have the wildest sex story nobody believes?',
  'Who is most likely to own the most sex toys?',
  'Who is most likely to have handcuffs just in case?',
  'Who is most likely to be freakier than they let on in public?',
  'Who is most likely to be vanilla until the lights go out?',
  'Who is most likely to always be the dominant one in bed?',
  'Who is most likely to always be the submissive one in bed?',
  'Who is most likely to have a praise kink?',
  'Who is most likely to talk the most dirty during sex?',
  'Who is most likely to send a voice note they immediately regret?',
  'Who is most likely to sext all day and then fall asleep when you pull up?',
  'Who is most likely to get horny at the worst possible moment?',
  'Who is most likely to hook up while their roommate is home?',
  'Who is most likely to have sex with the TV still on?',
  'Who is most likely to skip foreplay every single time?',
  'Who is most likely to cry after sex?',
  'Who is most likely to laugh during sex?',
  'Who is most likely to think about someone else during sex?',
  "Who is most likely to have a celebrity they'd actually leave their partner for?",
  'Who is most likely to have a hall pass list?',
  'Who is most likely to be the first one skinny dipping?',
  'Who is most likely to make out with a stranger in an Uber?',
  'Who is most likely to get a hickey before an important event?',
  'Who is most likely to show up to brunch with a hickey and no explanation?',
  'Who is most likely to hook up with their neighbor?',
  "Who is most likely to have a crush on a friend's partner?",
  'Who is most likely to spill who they hooked up with after two drinks?',
  'Who is most likely to keep a hookup secret forever?',
  'Who is most likely to accidentally confess feelings while drunk?',
  'Who is most likely to drunk text an ex?',
  'Who is most likely to wake up next to someone and ask "who are you?"?',
  'Who is most likely to have a finsta full of unhinged thirst content?',
  'Who is most likely to subscribe to someone they know on OnlyFans?',
  'Who is most likely to start an OnlyFans if they were broke enough?',
  'Who is most likely to read smut in public without shame?',
  'Who is most likely to own more lube than moisturizer?',
  'Who is most likely to google "how to be better in bed" before a date?',
  "Who is most likely to hook up in their parents' house while they're home?",
  'Who is most likely to get walked in on and keep going?',
  'Who is most likely to have the messiest drunk hookup story?',
  'Who is most likely to flirt with someone taken just for sport?',
  'Who is most likely to be a simp for the worst person possible?',
  'Who is most likely to catch an STD and still not learn their lesson?',
  'Who is most likely to forget protection and pray?',
  'Who is most likely to have a pregnancy scare story?',
  'Who is most likely to be down bad in the group chat at 3am?',
  'Who is most likely to agree to something unhinged on a dare and actually do it?',
  'Who is most likely to have a sex dream about someone in this room?',
]

export const MLT_QUESTION_COUNT = MLT_QUESTIONS.length

export function pickMltQuestions(count: number, usageCounts: Map<string, number> = new Map()): string[] {
  return pickLeastUsed(MLT_QUESTIONS, (question) => question, usageCounts, count)
}
