/** Built-in Most Likely To prompts */

import { pickLeastUsed } from '@/lib/question-picker'

export const MLT_QUESTIONS: string[] = [
  'Who is most likely to become famous?',
  'Who is most likely to forget someone\'s birthday?',
  'Who is most likely to win a dance-off?',
  'Who is most likely to start a group chat at 2am?',
  'Who is most likely to become a millionaire?',
  'Who is most likely to move to another country?',
  'Who is most likely to go viral for something random?',
  'Who is most likely to sleep through their alarm?',
  'Who is most likely to adopt ten pets?',
  'Who is most likely to write a book someday?',
  'Who is most likely to become a teacher?',
  'Who is most likely to start their own business?',
  'Who is most likely to win a game show?',
  'Who is most likely to get lost using GPS?',
  'Who is most likely to laugh at the wrong moment?',
  'Who is most likely to cry during a movie?',
  'Who is most likely to become president or prime minister?',
  'Who is most likely to survive a zombie apocalypse?',
  'Who is most likely to forget their wallet?',
  'Who is most likely to become a social media influencer?',
  'Who is most likely to eat dessert before dinner?',
  'Who is most likely to talk their way out of a speeding ticket?',
  'Who is most likely to double-text after being left on read?',
  'Who is most likely to accidentally like an old photo while scrolling someone\'s profile?',
  'Who is most likely to show up overdressed to a casual hangout?',
  'Who is most likely to show up underdressed to a formal event?',
  'Who is most likely to become a professional athlete?',
  'Who is most likely to win a Nobel Prize?',
  'Who is most likely to become a chef?',
  'Who is most likely to order the weirdest thing on the menu?',
  'Who is most likely to become a travel blogger?',
  'Who is most likely to miss their flight?',
  'Who is most likely to pack way too much for a weekend trip?',
  'Who is most likely to forget to pack a charger?',
  'Who is most likely to become a comedian?',
  'Who is most likely to tell the same story three times in one night?',
  'Who is most likely to become a doctor?',
  'Who is most likely to Google their symptoms and panic?',
  'Who is most likely to become an artist?',
  'Who is most likely to redecorate their room every month?',
  'Who is most likely to become a musician?',
  'Who is most likely to sing karaoke sober?',
  'Who is most likely to become a scientist?',
  'Who is most likely to explain a movie plot wrong with full confidence?',
  'Who is most likely to become a lawyer?',
  'Who is most likely to win an argument using facts nobody can verify?',
  'Who is most likely to become a therapist?',
  'Who is most likely to give advice they should take themselves?',
  'Who is most likely to become a pilot?',
  'Who is most likely to clap when the plane lands?',
  'Who is most likely to become a news anchor?',
  'Who is most likely to read the news out loud like a broadcaster?',
  'Who is most likely to become a professional gamer?',
  'Who is most likely to rage-quit a friendly game?',
  'Who is most likely to become a photographer?',
  'Who is most likely to take 200 photos of the same sunset?',
  'Who is most likely to become a fashion designer?',
  'Who is most likely to wear sunglasses indoors?',
  'Who is most likely to become a detective?',
  'Who is most likely to solve a mystery before anyone else?',
  'Who is most likely to become a life coach?',
  'Who is most likely to make a vision board and actually follow it?',
  'Who is most likely to become a park ranger?',
  'Who is most likely to befriend every dog at the park?',
  'Who is most likely to become a wedding planner?',
  'Who is most likely to cry at every wedding?',
  'Who is most likely to become a stand-up comedian?',
  'Who is most likely to laugh at their own joke first?',
  'Who is most likely to become a marathon runner?',
  'Who is most likely to sign up for a 5K and train for five minutes?',
  'Who is most likely to become a motivational speaker?',
  'Who is most likely to hype up the group before anything?',
  'Who is most likely to become a zookeeper?',
  'Who is most likely to name every animal they see?',
  'Who is most likely to become a librarian?',
  'Who is most likely to shush people in a movie theater?',
  'Who is most likely to become a weather reporter?',
  'Who is most likely to check the weather app ten times a day?',
  'Who is most likely to become a camp counselor?',
  'Who is most likely to lead every group activity?',
  'Who is most likely to become a video editor?',
  'Who is most likely to spend hours picking the perfect filter?',
  'Who is most likely to become a podcast host?',
  'Who is most likely to start a podcast and never release episode two?',
  'Who is most likely to become a trivia champion?',
  'Who is most likely to shout answers before the question is finished?',
  'Who is most likely to become a party planner?',
  'Who is most likely to bring snacks nobody asked for but everyone eats?',
  'Who is most likely to become a tour guide?',
  'Who is most likely to know a random fact about every landmark?',
  'Who is most likely to become a magician?',
  'Who is most likely to try a magic trick at a family dinner?',
  'Who is most likely to become an astronaut?',
  'Who is most likely to apply to space camp as an adult?',
  'Who is most likely to become a chef on a cooking show?',
  'Who is most likely to add hot sauce to everything?',
  'Who is most likely to become a professional organizer?',
  'Who is most likely to label every container in the kitchen?',
  'Who is most likely to become a substitute teacher?',
  'Who is most likely to get mistaken for the teacher on the first day?',
  'Who is most likely to become a camp fire storyteller?',
  'Who is most likely to make a ghost story too realistic?',
  'Who is most likely to become a meme creator?',
  'Who is most likely to send the perfect reaction GIF every time?',
  'Who is most likely to become a dance instructor?',
  'Who is most likely to start dancing when a good song comes on?',
  'Who is most likely to become a voice actor?',
  'Who is most likely to do impressions of everyone in the room?',
  'Who is most likely to become a game show host?',
  'Who is most likely to narrate life like a sports commentator?',
  'Who is most likely to become a parkour enthusiast?',
  'Who is most likely to try a backflip at a party?',
  'Who is most likely to become a plant parent with 50 houseplants?',
  'Who is most likely to name every houseplant?',
  'Who is most likely to become a thrift store legend?',
  'Who is most likely to find the best vintage jacket in the bin?',
  'Who is most likely to become a group chat admin forever?',
  'Who is most likely to mute the chat and forget to unmute?',
  'Who is most likely to become a holiday decorator extremist?',
  'Who is most likely to put up Christmas lights in November?',
  'Who is most likely to become a board game rule lawyer?',
  'Who is most likely to read the rulebook out loud?',
  'Who is most likely to become a road trip DJ?',
  'Who is most likely to play the same song on repeat for four hours?',
  'Who is most likely to become a professional napper?',
  'Who is most likely to fall asleep five minutes into a movie?',
  'Who is most likely to become a spelling bee champion?',
  'Who is most likely to correct everyone\'s grammar?',
  'Who is most likely to become a escape room record holder?',
  'Who is most likely to overthink a simple puzzle?',
  'Who is most likely to become a friendly neighborhood helper?',
  'Who is most likely to return a lost wallet with everything inside?',
  'Who is most likely to become a surprise party mastermind?',
  'Who is most likely to accidentally spoil a surprise?',
  'Who is most likely to become a group photo director?',
  'Who is most likely to take 47 photos to get one good group shot?',
  'Who is most likely to become a coffee shop regular with a usual order?',
  'Who is most likely to learn the barista\'s name before their coworker\'s?',
  'Who is most likely to become a midnight snack chef?',
  'Who is most likely to make a gourmet meal at 1am?',
  'Who is most likely to become a playlist curator for every mood?',
  'Who is most likely to make a playlist titled "vibes"?',
  'Who is most likely to become a pen pal with someone across the world?',
  'Who is most likely to keep every birthday card they ever received?',
  'Who is most likely to become a volunteer superstar?',
  'Who is most likely to sign up for everything and follow through?',
  'Who is most likely to become a local trivia night legend?',
  'Who is most likely to remember obscure facts from 2014?',
  'Who is most likely to become a comfort friend everyone calls first?',
  'Who is most likely to answer the phone at any hour?',
  'Who is most likely to become a holiday cookie champion?',
  'Who is most likely to burn the first batch and still serve them proudly?',
  'Who is most likely to become a group trip planner?',
  'Who is most likely to make the spreadsheet nobody asked for?',
  'Who is most likely to become a friendly rival in every game?',
  'Who is most likely to demand a rematch after losing?',
  'Who is most likely to become a human GPS?',
  'Who is most likely to remember every turn without looking?',
  'Who is most likely to become a champion gift giver?',
  'Who is most likely to remember a random detail from years ago?',
  'Who is most likely to become a morning person against all odds?',
  'Who is most likely to wake up early on vacation?',
  'Who is most likely to become a night owl who still makes every plan?',
  'Who is most likely to suggest one more round at midnight?',
  'Who is most likely to become a group hype person?',
  'Who is most likely to clap the loudest at a school play?',
  'Who is most likely to become a friendly ghost on Halloween?',
  'Who is most likely to go all out on a costume every year?',
  'Who is most likely to become a snow day optimist?',
  'Who is most likely to build the best snowman on the block?',
  'Who is most likely to become a summer camp legend?',
  'Who is most likely to win every camp talent show?',
  'Who is most likely to become a friend who remembers every inside joke?',
  'Who is most likely to quote the group chat IRL?',
  'Who is most likely to become a peacemaker when debates get heated?',
  'Who is most likely to change the subject with a snack suggestion?',
  'Who is most likely to become a first-to-arrive, last-to-leave party guest?',
  'Who is most likely to help clean up without being asked?',
  'Who is most likely to become a human encyclopedia for random hobbies?',
  'Who is most likely to go down a Wikipedia rabbit hole and report back?',
  'Who is most likely to become a champion parallel parker?',
  'Who is most likely to clap after a perfect parking job?',
  'Who is most likely to become a group nickname inventor?',
  'Who is most likely to give everyone a nickname that sticks?',
  'Who is most likely to become a board game night regular host?',
  'Who is most likely to own more games than shelves?',
  'Who is most likely to become a friendly competitor in mini golf?',
  'Who is most likely to celebrate a hole-in-one like the Olympics?',
  'Who is most likely to become a picnic planner?',
  'Who is most likely to bring a blanket, snacks, and speakers?',
  'Who is most likely to become a campfire song leader?',
  'Who is most likely to start a sing-along nobody planned?',
  'Who is most likely to become a museum day enthusiast?',
  'Who is most likely to read every plaque in the exhibit?',
  'Who is most likely to become a beach day MVP?',
  'Who is most likely to build the best sandcastle?',
  'Who is most likely to become a hiking buddy who never complains?',
  'Who is most likely to bring extra water for everyone?',
  'Who is most likely to become a movie marathon host?',
  'Who is most likely to pick the trilogy extended editions?',
  'Who is most likely to become a theme park ride repeat offender?',
  'Who is most likely to ride the roller coaster twice in a row?',
  'Who is most likely to become a New Year\'s resolution overachiever?',
  'Who is most likely to actually keep their resolution past February?',
  'Who is most likely to become a group cheer captain?',
  'Who is most likely to invent a chant on the spot?',
  'Who is most likely to become a friendly pen-clicker during thinking time?',
  'Who is most likely to tap a rhythm on the table during trivia?',
  'Who is most likely to become a champion thumb wrestler?',
  'Who is most likely to demand a best-of-three rematch?',
  'Who is most likely to become a human calendar for friend events?',
  'Who is most likely to remember every anniversary and plan ahead?',
  'Who is most likely to become a snack emergency responder?',
  'Who is most likely to have candy in their bag at all times?',
  'Who is most likely to become a group photographer?',
  'Who is most likely to insist on one more photo with good lighting?',
  'Who is most likely to become a friendly weather complainer?',
  'Who is most likely to say "it\'s too hot" and "it\'s too cold" in the same week?',
  'Who is most likely to become a champion gift wrapper?',
  'Who is most likely to use too much tape and make it beautiful?',
  'Who is most likely to become a board game teacher?',
  'Who is most likely to explain rules better than the box?',
  'Who is most likely to become a group trip snack treasurer?',
  'Who is most likely to collect money and buy snacks for the car?',
  'Who is most likely to become a friendly hype DJ for pregame playlists?',
  'Who is most likely to make a playlist called "LET\'S GO"?',
  'Who is most likely to become a champion charades actor?',
  'Who is most likely to mime so hard they pull a muscle?',
  'Who is most likely to become a trivia answer shouter?',
  'Who is most likely to know the capital of a country nobody asked about?',
  'Who is most likely to become a group meme historian?',
  'Who is most likely to find the perfect meme from three years ago?',
  'Who is most likely to become a friendly referee in every debate?',
  'Who is most likely to say "let\'s hear both sides"?',
  'Who is most likely to become a champion high-fiver?',
  'Who is most likely to celebrate small wins like championships?',
  'Who is most likely to become a group gratitude speaker?',
  'Who is most likely to give a toast that makes everyone smile?',
  'Who is most likely to become a human reminder app?',
  'Who is most likely to text "don\'t forget" about something you already forgot?',
  'Who is most likely to become a friendly icebreaker leader?',
  'Who is most likely to start with "okay quick question" at every hangout?',
  'Who is most likely to become a champion team picker?',
  'Who is most likely to make balanced teams for every game?',
  'Who is most likely to become a group tradition starter?',
  'Who is most likely to invent a new holiday for the friend group?',
  'Who is most likely to become a friendly optimist in bad weather?',
  'Who is most likely to say "at least it\'s an adventure"?',
  'Who is most likely to become a champion sticker collector?',
  'Who is most likely to still have stickers from elementary school?',
  'Who is most likely to become a group laugh track?',
  'Who is most likely to laugh so hard everyone else starts laughing?',
  'Who is most likely to become a friendly dare accepter?',
  'Who is most likely to actually do the silly dare?',
  'Who is most likely to become a champion nap strategist?',
  'Who is most likely to find the comfiest couch spot instantly?',
  'Who is most likely to become a group map reader?',
  'Who is most likely to rotate the phone map the wrong way first?',
  'Who is most likely to become a friendly food sharer?',
  'Who is most likely to say "want a bite?" before anyone asks?',
  'Who is most likely to become a champion umbrella lender?',
  'Who is most likely to have an extra umbrella nobody knew about?',
  'Who is most likely to become a group timekeeper?',
  'Who is most likely to say "we should leave in ten minutes" and be right?',
  'Who is most likely to become a friendly hype texter before every plan?',
  'Who is most likely to send "still on for tonight?" with perfect timing?',
  'Who is most likely to become a champion reunion planner?',
  'Who is most likely to organize the friend group meetup months ahead?',
  'Who is most likely to become a group mascot energy person?',
  'Who is most likely to make everyone feel glad they came?',
]

export const MLT_QUESTION_COUNT = MLT_QUESTIONS.length

export function pickMltQuestions(count: number, usageCounts: Map<string, number> = new Map()): string[] {
  return pickLeastUsed(MLT_QUESTIONS, (question) => question, usageCounts, count)
}
