/** Built-in Never Have I Ever prompts (prefix added in UI). */

import { pickLeastUsed } from '@/lib/question-picker'

export const NHIE_QUESTIONS: string[] = [
  'been skydiving',
  'gone skinny dipping',
  'kissed a stranger',
  'lied about my age',
  'pretended to be sick to skip school or work',
  'sent a text to the wrong person',
  'fallen asleep in class',
  'forgotten someone\'s name right after meeting them',
  'eaten food off the floor',
  'regifted a present',
  'stalked an ex on social media',
  'cried during a movie in a theater',
  'laughed so hard I cried',
  'been on a blind date',
  'ghosted someone',
  'been ghosted',
  'had a crush on a friend\'s sibling',
  'broken a bone',
  'gotten a tattoo',
  'gotten a piercing somewhere other than my ears',
  'dyed my hair a wild color',
  'been kicked out of a bar or club',
  'sneaked into a movie',
  'cheated on a test',
  'been in a physical fight',
  'pulled an all-nighter for fun',
  'fallen asleep on public transit and missed my stop',
  'walked into a glass door',
  'tripped in public and played it cool',
  'sung karaoke sober',
  'sung karaoke drunk',
  'been to a music festival',
  'met a celebrity',
  'been on TV',
  'posted something I immediately regretted',
  'deleted a post out of embarrassment',
  'been catfished or almost catfished online',
  'used a fake ID',
  'lied on a resume',
  'called in sick when I was perfectly fine',
  'eaten an entire pizza by myself',
  'hidden snacks from my roommate or partner',
  'snooped through someone\'s phone',
  'read someone\'s diary or journal',
  'eavesdropped on a conversation and joined in',
  'pretended to know a song when I didn\'t',
  'Googled myself',
  'had a wardrobe malfunction in public',
  'worn the same outfit two days in a row',
  'forgotten my own birthday for a moment',
  'double-texted after being left on read',
  'liked an old photo while stalking someone\'s profile',
  'been stood up on a date',
  'been in love with two people at once',
  'said "I love you" first',
  'had my heart broken badly',
  'broken someone\'s heart',
  'kissed more than one person in the same night',
  'had a one-night stand',
  'been in a long-distance relationship',
  'moved to a new city without knowing anyone',
  'traveled alone internationally',
  'missed a flight',
  'lost my passport or wallet while traveling',
  'gotten food poisoning on vacation',
  'swam in the ocean at night',
  'camped in the wilderness',
  'been bitten by a wild animal',
  'been chased by an animal',
  'had a paranormal experience I can\'t explain',
  'tried to contact the dead (Ouija, medium, etc.)',
  'pranked someone so hard they got upset',
  'been pranked so hard I got upset',
  'ruined a surprise party by accident',
  'forgotten an anniversary or birthday',
  're-gifted something and gotten caught',
  'pretended to like a gift I hated',
  'faked an orgasm',
  'had a dream about someone in this room',
  'had a crush on a teacher or boss',
  'dated a coworker',
  'been fired or let go from a job',
  'quit a job without another one lined up',
  'cried at work',
  'fallen asleep during a meeting',
  'sent a work email to the wrong person',
  'accidentally replied all',
  'been drunk at work (or a work event)',
  'hooked up at a wedding',
  'cried at a wedding',
  'been the drunk person at a wedding',
  'made a toast that went badly',
  'forgotten lines during a speech',
  'been in a school play or talent show',
  'forgotten choreography or lyrics on stage',
  'won a competition I didn\'t expect to win',
  'lost a competition I expected to win',
  'bet money on something stupid',
  'won big on a bet or game',
  'lost big on a bet or game',
  'tried a fad diet',
  'gone vegan or vegetarian for at least a month',
  'pulled a muscle trying something athletic',
  'run a marathon or half marathon',
  'been to the emergency room for something embarrassing',
  'fainted in public',
  'thrown up in public (not as a kid)',
  'had food stuck in my teeth during an important moment',
  'walked around with toilet paper on my shoe',
  'waved back at someone who wasn\'t waving at me',
]

export const NHIE_QUESTION_COUNT = NHIE_QUESTIONS.length

export function pickNhieQuestions(count: number, usageCounts: Map<string, number> = new Map()): string[] {
  return pickLeastUsed(NHIE_QUESTIONS, (question) => question, usageCounts, count)
}
