-- RLS lockdown: Snake & Ladder (canary for the server-authoritative write model).
--
-- Before: both tables used `FOR ALL USING(true) WITH CHECK(true)`, so any client
-- holding the public anon key could mutate turns, positions, and winners directly,
-- bypassing the game APIs (cheating/griefing).
--
-- After: anon may READ (realtime subscriptions need this) but cannot write. Every
-- write now goes through a server route using the service role, which bypasses RLS:
--   - /api/snake-and-ladder/roll        — authorized by resume_token (assertPlayer)
--   - /api/snake-and-ladder/expire-turn — system/timer, only acts past the deadline
--   - /api/games/[code]/start           — host-authorized (initialize)
--   - /api/games/[code]/play-again      — host-authorized (clear)
--   - /api/players (DELETE)             — host- or player-session authorized (remove)
--
-- See docs/rls-hardening.md for the full plan and rollout sequence.

alter table snake_ladder_sessions enable row level security;
drop policy if exists "public_snake_ladder_sessions" on snake_ladder_sessions;
drop policy if exists "snake_ladder_sessions_read" on snake_ladder_sessions;
create policy "snake_ladder_sessions_read" on snake_ladder_sessions for select using (true);

alter table snake_ladder_player_state enable row level security;
drop policy if exists "public_snake_ladder_player_state" on snake_ladder_player_state;
drop policy if exists "snake_ladder_player_state_read" on snake_ladder_player_state;
create policy "snake_ladder_player_state_read" on snake_ladder_player_state for select using (true);

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted — restores the permissive policies if a regression appears).
-- Apply as a new forward migration; do NOT edit this file after it has shipped.
--
-- drop policy if exists "snake_ladder_sessions_read" on snake_ladder_sessions;
-- create policy "public_snake_ladder_sessions" on snake_ladder_sessions
--   for all using (true) with check (true);
-- drop policy if exists "snake_ladder_player_state_read" on snake_ladder_player_state;
-- create policy "public_snake_ladder_player_state" on snake_ladder_player_state
--   for all using (true) with check (true);
-- ----------------------------------------------------------------------------
