-- RLS lockdown: Tic-Tac-Toe (server-authoritative write model).
--
-- Before: tic_tac_toe_sessions used `FOR ALL USING(true) WITH CHECK(true)`, so any
-- client holding the public anon key could mutate turns, the board, and the winner
-- directly, bypassing the game APIs (cheating/griefing).
--
-- After: anon may READ (realtime subscriptions need this) but cannot write. Every
-- write now goes through a server route using the service role, which bypasses RLS:
--   - /api/tic-tac-toe/move        — authorized by resume_token (assertPlayer)
--   - /api/tic-tac-toe/expire-turn — system/timer, only acts past the deadline
--   - /api/games/[code]/start      — host-authorized (initialize)
--   - /api/games/[code]/play-again — host-authorized (clear)
--   - /api/players (DELETE)        — host- or player-session authorized (remove)
--
-- See docs/rls-hardening.md for the full plan and rollout sequence.

alter table tic_tac_toe_sessions enable row level security;
drop policy if exists "public_tic_tac_toe_sessions" on tic_tac_toe_sessions;
drop policy if exists "tic_tac_toe_sessions_read" on tic_tac_toe_sessions;
create policy "tic_tac_toe_sessions_read" on tic_tac_toe_sessions for select using (true);

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted — restores the permissive policy if a regression appears).
-- Apply as a new forward migration; do NOT edit this file after it has shipped.
--
-- drop policy if exists "tic_tac_toe_sessions_read" on tic_tac_toe_sessions;
-- create policy "public_tic_tac_toe_sessions" on tic_tac_toe_sessions
--   for all using (true) with check (true);
-- ----------------------------------------------------------------------------
