-- RLS lockdown: Yahtzee (server-authoritative write model).
--
-- Before: yahtzee_sessions and yahtzee_player_scores used `FOR ALL USING(true)
-- WITH CHECK(true)`, so any client holding the public anon key could mutate
-- dice, held flags, turns, scores, and the winner directly, bypassing the game
-- APIs (cheating/griefing).
--
-- After: anon may READ (realtime subscriptions need this) but cannot write. Every
-- write now goes through a server route using the service role, which bypasses RLS:
--   - /api/yahtzee/roll        — authorized by resume_token (assertPlayer)
--   - /api/yahtzee/hold        — authorized by resume_token (assertPlayer)
--   - /api/yahtzee/score       — authorized by resume_token (assertPlayer)
--   - /api/yahtzee/expire-turn — system/timer, only acts past the deadline
--   - /api/games/[code]/start      — host-authorized (initialize)
--   - /api/games/[code]/play-again — host-authorized (clear)
--   - /api/players (DELETE)        — host- or player-session authorized (remove)
--
-- See docs/rls-hardening.md for the full plan and rollout sequence.

alter table yahtzee_sessions enable row level security;
drop policy if exists "public_yahtzee_sessions" on yahtzee_sessions;
drop policy if exists "yahtzee_sessions_read" on yahtzee_sessions;
create policy "yahtzee_sessions_read" on yahtzee_sessions for select using (true);

alter table yahtzee_player_scores enable row level security;
drop policy if exists "public_yahtzee_player_scores" on yahtzee_player_scores;
drop policy if exists "yahtzee_player_scores_read" on yahtzee_player_scores;
create policy "yahtzee_player_scores_read" on yahtzee_player_scores for select using (true);

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted — restores the permissive policy if a regression appears).
-- Apply as a new forward migration; do NOT edit this file after it has shipped.
--
-- drop policy if exists "yahtzee_sessions_read" on yahtzee_sessions;
-- create policy "public_yahtzee_sessions" on yahtzee_sessions
--   for all using (true) with check (true);
--
-- drop policy if exists "yahtzee_player_scores_read" on yahtzee_player_scores;
-- create policy "public_yahtzee_player_scores" on yahtzee_player_scores
--   for all using (true) with check (true);
-- ----------------------------------------------------------------------------
