-- RLS lockdown: Whot (server-authoritative write model).
--
-- Before: both tables used `FOR ALL USING(true) WITH CHECK(true)`, so any client
-- holding the public anon key could mutate turns, hands, the pile, and the winner
-- directly, bypassing the game APIs (cheating/griefing).
--
-- After: anon may READ (realtime subscriptions need this) but cannot write. Every
-- write now goes through a server route using the service role, which bypasses RLS:
--   - /api/whot/play          — authorized by resume_token (assertPlayer)
--   - /api/whot/draw          — authorized by resume_token (assertPlayer)
--   - /api/whot/choose        — authorized by resume_token (assertPlayer)
--   - /api/whot/expire-turn   — system/timer, only acts past the deadline
--   - /api/games/[code]/start      — host-authorized (initialize)
--   - /api/games/[code]/play-again — host-authorized (clear)
--   - /api/players (DELETE)        — host- or player-session authorized (remove)
--
-- See docs/rls-hardening.md for the full plan and rollout sequence.

alter table whot_sessions enable row level security;
drop policy if exists "public_whot_sessions" on whot_sessions;
drop policy if exists "whot_sessions_read" on whot_sessions;
create policy "whot_sessions_read" on whot_sessions for select using (true);

alter table whot_player_hands enable row level security;
drop policy if exists "public_whot_player_hands" on whot_player_hands;
drop policy if exists "whot_player_hands_read" on whot_player_hands;
create policy "whot_player_hands_read" on whot_player_hands for select using (true);

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted — restores the permissive policies if a regression appears).
-- Apply as a new forward migration; do NOT edit this file after it has shipped.
--
-- drop policy if exists "whot_sessions_read" on whot_sessions;
-- create policy "public_whot_sessions" on whot_sessions
--   for all using (true) with check (true);
-- drop policy if exists "whot_player_hands_read" on whot_player_hands;
-- create policy "public_whot_player_hands" on whot_player_hands
--   for all using (true) with check (true);
-- ----------------------------------------------------------------------------
