-- RLS lockdown: Ludo (server-authoritative write model).
--
-- Before: both tables used `FOR ALL USING(true) WITH CHECK(true)`, so any client
-- holding the public anon key could mutate turns, piece positions, dice, and winners
-- directly, bypassing the game APIs (cheating/griefing).
--
-- After: anon may READ (realtime subscriptions need this) but cannot write. Every
-- write now goes through a server route using the service role, which bypasses RLS:
--   - /api/ludo/roll          — authorized by resume_token (assertPlayer)
--   - /api/ludo/move          — authorized by resume_token (assertPlayer)
--   - /api/ludo/expire-turn   — system/timer, only acts past the deadline
--   - /api/games/[code]/start — host-authorized (initialize)
--   - /api/games/[code]/play-again — host-authorized (clear)
--   - /api/players (DELETE)   — host- or player-session authorized (remove)
--
-- See docs/rls-hardening.md for the full plan and rollout sequence.

alter table ludo_sessions enable row level security;
drop policy if exists "public_ludo_sessions" on ludo_sessions;
drop policy if exists "ludo_sessions_read" on ludo_sessions;
create policy "ludo_sessions_read" on ludo_sessions for select using (true);

alter table ludo_player_state enable row level security;
drop policy if exists "public_ludo_player_state" on ludo_player_state;
drop policy if exists "ludo_player_state_read" on ludo_player_state;
create policy "ludo_player_state_read" on ludo_player_state for select using (true);

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted — restores the permissive policies if a regression appears).
-- Apply as a new forward migration; do NOT edit this file after it has shipped.
--
-- drop policy if exists "ludo_sessions_read" on ludo_sessions;
-- create policy "public_ludo_sessions" on ludo_sessions
--   for all using (true) with check (true);
-- drop policy if exists "ludo_player_state_read" on ludo_player_state;
-- create policy "public_ludo_player_state" on ludo_player_state
--   for all using (true) with check (true);
-- ----------------------------------------------------------------------------
