-- RLS lockdown: Chess (server-authoritative write model).
--
-- Before: chess_sessions used `FOR ALL USING(true) WITH CHECK(true)`, so any
-- client holding the public anon key could mutate turns, the board, and the winner
-- directly, bypassing the game APIs (cheating/griefing).
--
-- After: anon may READ (realtime subscriptions need this) but cannot write. Every
-- write now goes through a server route using the service role, which bypasses RLS:
--   - /api/chess/move          — authorized by resume_token (assertPlayer)
--   - /api/chess/resign        — authorized by resume_token (assertPlayer)
--   - /api/chess/expire-turn   — system/timer, only acts past the deadline
--   - /api/games/[code]/start  — host-authorized (initialize)
--   - /api/games/[code]/play-again — host-authorized (clear)
--   - /api/players (DELETE)    — host- or player-session authorized (remove)
--
-- See docs/rls-hardening.md for the full plan and rollout sequence.

alter table chess_sessions enable row level security;
drop policy if exists "public_chess_sessions" on chess_sessions;
drop policy if exists "chess_sessions_read" on chess_sessions;
create policy "chess_sessions_read" on chess_sessions for select using (true);

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted — restores the permissive policy if a regression appears).
-- Apply as a new forward migration; do NOT edit this file after it has shipped.
--
-- drop policy if exists "chess_sessions_read" on chess_sessions;
-- create policy "public_chess_sessions" on chess_sessions
--   for all using (true) with check (true);
-- ----------------------------------------------------------------------------
