-- RLS lockdown: Monopoly (server-authoritative write model).
--
-- Before: monopoly_boards and monopoly_player_state used `FOR ALL USING(true)
-- WITH CHECK(true)`, so any client holding the public anon key could mutate
-- positions, cash, property ownership, buildings, dice, turns, trades, and the
-- winner directly, bypassing the game APIs (cheating/griefing).
--
-- After: anon may READ (realtime subscriptions need this) but cannot write. Every
-- write now goes through a server route using the service role, which bypasses RLS:
--   - /api/monopoly/roll         — authorized by resume_token (assertPlayer)
--   - /api/monopoly/buy          — authorized by resume_token (assertPlayer)
--   - /api/monopoly/build        — authorized by resume_token (assertPlayer)
--   - /api/monopoly/mortgage     — authorized by resume_token (assertPlayer)
--   - /api/monopoly/jail         — authorized by resume_token (assertPlayer)
--   - /api/monopoly/rent         — authorized by resume_token (assertPlayer)
--   - /api/monopoly/auction      — authorized by resume_token (assertPlayer)
--   - /api/monopoly/trade        — authorized by resume_token (assertPlayer)
--   - /api/monopoly/forfeit      — authorized by resume_token (assertPlayer)
--   - /api/monopoly/settle-debt  — authorized by resume_token (assertPlayer)
--   - /api/monopoly/expire-turn  — system/timer, only acts past the deadline
--   - /api/games/[code]/expire-monopoly       — system/timer, only acts past session expiry
--   - /api/games/[code]/extend-monopoly-time  — host-authorized (host_token)
--   - /api/games/[code]/start      — host-authorized (initialize)
--   - /api/games/[code]/play-again — host-authorized (clear)
--   - /api/players (DELETE)        — host- or player-session authorized (remove)
--
-- See docs/rls-hardening.md for the full plan and rollout sequence.

alter table monopoly_boards enable row level security;
drop policy if exists "public_monopoly_boards" on monopoly_boards;
drop policy if exists "monopoly_boards_read" on monopoly_boards;
create policy "monopoly_boards_read" on monopoly_boards for select using (true);

alter table monopoly_player_state enable row level security;
drop policy if exists "public_monopoly_player_state" on monopoly_player_state;
drop policy if exists "monopoly_player_state_read" on monopoly_player_state;
create policy "monopoly_player_state_read" on monopoly_player_state for select using (true);

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted — restores the permissive policy if a regression appears).
-- Apply as a new forward migration; do NOT edit this file after it has shipped.
--
-- drop policy if exists "monopoly_boards_read" on monopoly_boards;
-- create policy "public_monopoly_boards" on monopoly_boards
--   for all using (true) with check (true);
--
-- drop policy if exists "monopoly_player_state_read" on monopoly_player_state;
-- create policy "public_monopoly_player_state" on monopoly_player_state
--   for all using (true) with check (true);
-- ----------------------------------------------------------------------------
