-- RLS lockdown: Scrabble (server-authoritative write model).
--
-- Before: scrabble_sessions and scrabble_player_state used `FOR ALL USING(true)
-- WITH CHECK(true)`, so any client holding the public anon key could mutate the
-- board, racks, turns, scores, and the winner directly, bypassing the game APIs
-- (cheating/griefing).
--
-- After: anon may READ (realtime subscriptions need this) but cannot write. Every
-- write now goes through a server route using the service role, which bypasses RLS:
--   - /api/scrabble/play           — authorized by resume_token (assertPlayer)
--   - /api/scrabble/exchange       — authorized by resume_token (assertPlayer)
--   - /api/scrabble/pass           — authorized by resume_token (assertPlayer)
--   - /api/scrabble/expire-turn    — system/timer, only acts past the deadline
--   - /api/games/[code]/expire-scrabble       — system/timer, only acts past the deadline
--   - /api/games/[code]/extend-scrabble-time  — host-authorized (host_token)
--   - /api/games/[code]/start      — host-authorized (initialize)
--   - /api/games/[code]/play-again — host-authorized (clear)
--   - /api/players (DELETE)        — host- or player-session authorized (remove)
--
-- See docs/rls-hardening.md for the full plan and rollout sequence.

alter table scrabble_sessions enable row level security;
drop policy if exists "public_scrabble_sessions" on scrabble_sessions;
drop policy if exists "scrabble_sessions_read" on scrabble_sessions;
create policy "scrabble_sessions_read" on scrabble_sessions for select using (true);

alter table scrabble_player_state enable row level security;
drop policy if exists "public_scrabble_player_state" on scrabble_player_state;
drop policy if exists "scrabble_player_state_read" on scrabble_player_state;
create policy "scrabble_player_state_read" on scrabble_player_state for select using (true);

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted — restores the permissive policy if a regression appears).
-- Apply as a new forward migration; do NOT edit this file after it has shipped.
--
-- drop policy if exists "scrabble_sessions_read" on scrabble_sessions;
-- create policy "public_scrabble_sessions" on scrabble_sessions
--   for all using (true) with check (true);
--
-- drop policy if exists "scrabble_player_state_read" on scrabble_player_state;
-- create policy "public_scrabble_player_state" on scrabble_player_state
--   for all using (true) with check (true);
-- ----------------------------------------------------------------------------
