-- RLS lockdown: Trivia (server-authoritative write model).
--
-- Before: trivia_answers used `FOR ALL USING(true) WITH CHECK(true)`, so any
-- client holding the public anon key could insert, edit, or delete answer rows
-- directly — forging answers, points, correctness, and response times, bypassing
-- the game APIs (cheating/griefing).
--
-- After: anon may READ (realtime subscriptions and leaderboards need this) but
-- cannot write. Every write now goes through a server route using the service
-- role, which bypasses RLS:
--   - /api/trivia/answer  — authorized by resume_token (assertPlayer)
--   - /api/trivia/advance — system sync; host-authorized for force advance
--   - /api/games/[code]/next-round — host-authorized (shared round advance)
--   - /api/games/[code]/start      — host-authorized (initialize)
--   - /api/games/[code]/play-again — host-authorized (clear)
--   - /api/players (DELETE)        — host- or player-session authorized (remove)
--
-- See docs/rls-hardening.md for the full plan and rollout sequence.

alter table trivia_answers enable row level security;
drop policy if exists "public_trivia_answers" on trivia_answers;
drop policy if exists "trivia_answers_read" on trivia_answers;
create policy "trivia_answers_read" on trivia_answers for select using (true);

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted — restores the permissive policy if a regression appears).
-- Apply as a new forward migration; do NOT edit this file after it has shipped.
--
-- drop policy if exists "trivia_answers_read" on trivia_answers;
-- create policy "public_trivia_answers" on trivia_answers
--   for all using (true) with check (true);
-- ----------------------------------------------------------------------------
