-- RLS lockdown: Two Truths and a Lie (server-authoritative write model).
--
-- Before: ttl_statements and ttl_guesses used `FOR ALL USING(true)
-- WITH CHECK(true)`, so any client holding the public anon key could write or
-- overwrite anyone's statements (including which one is the lie), forge guesses,
-- or award points directly, bypassing the game APIs (cheating/griefing).
--
-- After: anon may READ (realtime subscriptions need this) but cannot write. Every
-- write now goes through a server route using the service role, which bypasses RLS:
--   - /api/two-truths/statements  — authorized by resume_token (assertPlayer)
--   - /api/two-truths/guess       — authorized by resume_token (assertPlayer)
--   - /api/two-truths/advance     — host-authorized (round/game sync)
--   - /api/games/[code]/start      — host-authorized (seeds ttl_statements rounds)
--   - /api/games/[code]/play-again — host-authorized (clear)
--   - /api/players (DELETE)        — host- or player-session authorized (remove)
--
-- See docs/rls-hardening.md for the full plan and rollout sequence.

alter table ttl_statements enable row level security;
drop policy if exists "public_ttl_statements" on ttl_statements;
drop policy if exists "ttl_statements_read" on ttl_statements;
create policy "ttl_statements_read" on ttl_statements for select using (true);

alter table ttl_guesses enable row level security;
drop policy if exists "public_ttl_guesses" on ttl_guesses;
drop policy if exists "ttl_guesses_read" on ttl_guesses;
create policy "ttl_guesses_read" on ttl_guesses for select using (true);

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted — restores the permissive policy if a regression appears).
-- Apply as a new forward migration; do NOT edit this file after it has shipped.
--
-- drop policy if exists "ttl_statements_read" on ttl_statements;
-- create policy "public_ttl_statements" on ttl_statements
--   for all using (true) with check (true);
--
-- drop policy if exists "ttl_guesses_read" on ttl_guesses;
-- create policy "public_ttl_guesses" on ttl_guesses
--   for all using (true) with check (true);
-- ----------------------------------------------------------------------------
