-- RLS lockdown: Sudoku (server-authoritative write model).
--
-- Before: sudoku_submissions used `FOR ALL USING(true) WITH CHECK(true)`, so any
-- client holding the public anon key could insert/forge block submissions, scores,
-- and is_correct flags directly, bypassing the game API (cheating/griefing).
--
-- After: anon may READ (realtime subscriptions need this) but cannot write. Every
-- write now goes through a server route using the service role, which bypasses RLS:
--   - /api/sudoku/submit            — authorized by resume_token (assertPlayer),
--                                      writes via the sudoku_submit_block RPC
--   - /api/games/[code]/start       — host-authorized (initialize)
--   - /api/games/[code]/play-again  — host-authorized (clear)
--   - /api/players (DELETE)         — host- or player-session authorized (remove)
--
-- Note: sudoku_submit_block is SECURITY DEFINER, so the RPC's own writes run as the
-- function owner and are not subject to RLS regardless of this change. We lock the
-- table anyway for defense in depth — direct anon writes outside the RPC are blocked.
--
-- The companion table sudoku_solutions (INSERT policy from 0103) is intentionally
-- left unchanged in this migration.
--
-- See docs/rls-hardening.md for the full plan and rollout sequence.

alter table sudoku_submissions enable row level security;
drop policy if exists "public_sudoku_submissions" on sudoku_submissions;
drop policy if exists "sudoku_submissions_read" on sudoku_submissions;
create policy "sudoku_submissions_read" on sudoku_submissions for select using (true);

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted — restores the permissive policy if a regression appears).
-- Apply as a new forward migration; do NOT edit this file after it has shipped.
--
-- drop policy if exists "sudoku_submissions_read" on sudoku_submissions;
-- create policy "public_sudoku_submissions" on sudoku_submissions
--   for all using (true) with check (true);
-- ----------------------------------------------------------------------------
