-- RLS lockdown: Word Hunt (server-authoritative write model).
--
-- Before: word_hunt_submissions used `FOR ALL USING(true) WITH CHECK(true)`, so any
-- client holding the public anon key could insert/forge word submissions, paths,
-- and points directly, bypassing the game API (cheating/griefing).
--
-- After: anon may READ (realtime subscriptions need this) but cannot write. Every
-- write now goes through a server route using the service role, which bypasses RLS:
--   - /api/word-hunt/submit         — authorized by resume_token (assertPlayer)
--   - /api/games/[code]/play-again  — host-authorized (clear)
--   - /api/players (DELETE)         — host- or player-session authorized (remove)
--
-- See docs/rls-hardening.md for the full plan and rollout sequence.

alter table word_hunt_submissions enable row level security;
drop policy if exists "public_word_hunt_submissions" on word_hunt_submissions;
drop policy if exists "word_hunt_submissions_read" on word_hunt_submissions;
create policy "word_hunt_submissions_read" on word_hunt_submissions for select using (true);

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted — restores the permissive policy if a regression appears).
-- Apply as a new forward migration; do NOT edit this file after it has shipped.
--
-- drop policy if exists "word_hunt_submissions_read" on word_hunt_submissions;
-- create policy "public_word_hunt_submissions" on word_hunt_submissions
--   for all using (true) with check (true);
-- ----------------------------------------------------------------------------
