-- RLS lockdown: Codewords (server-authoritative write model).
--
-- Before: codewords_boards, codewords_player_roles, codewords_guesses and
-- codewords_messages used `FOR ALL USING(true) WITH CHECK(true)`, so any client
-- holding the public anon key could mutate the board (reveal cells, set the
-- winner, swap turns), reassign teams/roles, forge guesses, or post chat as
-- anyone — bypassing the game APIs (cheating/griefing).
--
-- After: anon may READ (realtime subscriptions need this) but cannot write. Every
-- write now goes through a server route using the service role, which bypasses RLS:
--   - /api/codewords/role            — authorized by resume_token (assertPlayer)
--   - /api/codewords/clue            — authorized by resume_token (assertPlayer)
--   - /api/codewords/guess           — authorized by resume_token (assertPlayer)
--   - /api/codewords/end-turn        — authorized by resume_token (assertPlayer)
--   - /api/codewords/chat            — authorized by resume_token (assertPlayer)
--   - /api/codewords/expire-turn     — system/timer, only acts past the deadline
--   - /api/codewords/host-role       — host-authorized (assign/unassign teams)
--   - /api/codewords/timers          — host-authorized (lobby settings)
--   - /api/codewords/randomize-teams — host-authorized (shuffle)
--   - /api/games/[code]/start        — host-authorized (initialize board/roles)
--   - /api/games/[code]/play-again   — host-authorized (clear)
--   - /api/players (DELETE)          — host- or player-session authorized (remove)
--
-- See docs/rls-hardening.md for the full plan and rollout sequence.

alter table codewords_boards enable row level security;
drop policy if exists "public_codewords_boards" on codewords_boards;
drop policy if exists "codewords_boards_read" on codewords_boards;
create policy "codewords_boards_read" on codewords_boards for select using (true);

alter table codewords_player_roles enable row level security;
drop policy if exists "public_codewords_player_roles" on codewords_player_roles;
drop policy if exists "codewords_player_roles_read" on codewords_player_roles;
create policy "codewords_player_roles_read" on codewords_player_roles for select using (true);

alter table codewords_guesses enable row level security;
drop policy if exists "public_codewords_guesses" on codewords_guesses;
drop policy if exists "codewords_guesses_read" on codewords_guesses;
create policy "codewords_guesses_read" on codewords_guesses for select using (true);

alter table codewords_messages enable row level security;
drop policy if exists "public_codewords_messages" on codewords_messages;
drop policy if exists "codewords_messages_read" on codewords_messages;
create policy "codewords_messages_read" on codewords_messages for select using (true);

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted — restores the permissive policy if a regression appears).
-- Apply as a new forward migration; do NOT edit this file after it has shipped.
--
-- drop policy if exists "codewords_boards_read" on codewords_boards;
-- create policy "public_codewords_boards" on codewords_boards
--   for all using (true) with check (true);
--
-- drop policy if exists "codewords_player_roles_read" on codewords_player_roles;
-- create policy "public_codewords_player_roles" on codewords_player_roles
--   for all using (true) with check (true);
--
-- drop policy if exists "codewords_guesses_read" on codewords_guesses;
-- create policy "public_codewords_guesses" on codewords_guesses
--   for all using (true) with check (true);
--
-- drop policy if exists "codewords_messages_read" on codewords_messages;
-- create policy "public_codewords_messages" on codewords_messages
--   for all using (true) with check (true);
-- ----------------------------------------------------------------------------
