-- RLS lockdown: Describe It / Text Charades (server-authoritative write model).
--
-- Before: describe_it_sessions, describe_it_players, describe_it_words and
-- describe_it_guesses used `FOR ALL USING(true) WITH CHECK(true)`, so any client
-- holding the public anon key could mutate the session (swap turns, set the
-- describer, reveal/skip words, set the winner), reassign teams, forge logged
-- words, or fake guesses and scores — bypassing the game APIs (cheating/griefing).
--
-- After: anon may READ (realtime subscriptions need this) but cannot write. Every
-- write now goes through a server route using the service role, which bypasses RLS:
--   - /api/describe-it/team        — authorized by resume_token (assertPlayer)
--   - /api/describe-it/clue        — authorized by resume_token (assertPlayer)
--   - /api/describe-it/guess       — authorized by resume_token (assertPlayer)
--   - /api/describe-it/skip        — authorized by resume_token (assertPlayer)
--   - /api/describe-it/expire-turn — system/timer, only acts past the deadline
--   - /api/describe-it/tick        — system/timer, CRON_SECRET-authorized
--   - /api/describe-it/advance     — host-authorized force; else only past the break
--   - /api/describe-it/balance     — host-authorized (auto-balance teams)
--   - /api/describe-it/settings    — host-authorized (lobby settings)
--   - /api/games/[code]/start      — host-authorized (initialize session/teams)
--   - /api/games/[code]/play-again — host-authorized (clear)
--   - /api/players (DELETE)        — host- or player-session authorized (remove)
--
-- See docs/rls-hardening.md for the full plan and rollout sequence.

alter table describe_it_sessions enable row level security;
drop policy if exists "public_describe_it_sessions" on describe_it_sessions;
drop policy if exists "describe_it_sessions_read" on describe_it_sessions;
create policy "describe_it_sessions_read" on describe_it_sessions for select using (true);

alter table describe_it_players enable row level security;
drop policy if exists "public_describe_it_players" on describe_it_players;
drop policy if exists "describe_it_players_read" on describe_it_players;
create policy "describe_it_players_read" on describe_it_players for select using (true);

alter table describe_it_words enable row level security;
drop policy if exists "public_describe_it_words" on describe_it_words;
drop policy if exists "describe_it_words_read" on describe_it_words;
create policy "describe_it_words_read" on describe_it_words for select using (true);

alter table describe_it_guesses enable row level security;
drop policy if exists "public_describe_it_guesses" on describe_it_guesses;
drop policy if exists "describe_it_guesses_read" on describe_it_guesses;
create policy "describe_it_guesses_read" on describe_it_guesses for select using (true);

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted — restores the permissive policy if a regression appears).
-- Apply as a new forward migration; do NOT edit this file after it has shipped.
--
-- drop policy if exists "describe_it_sessions_read" on describe_it_sessions;
-- create policy "public_describe_it_sessions" on describe_it_sessions
--   for all using (true) with check (true);
--
-- drop policy if exists "describe_it_players_read" on describe_it_players;
-- create policy "public_describe_it_players" on describe_it_players
--   for all using (true) with check (true);
--
-- drop policy if exists "describe_it_words_read" on describe_it_words;
-- create policy "public_describe_it_words" on describe_it_words
--   for all using (true) with check (true);
--
-- drop policy if exists "describe_it_guesses_read" on describe_it_guesses;
-- create policy "public_describe_it_guesses" on describe_it_guesses
--   for all using (true) with check (true);
-- ----------------------------------------------------------------------------
