-- RLS lockdown: Bingo (server-authoritative write model).
--
-- Before: bingo_cards, bingo_called_numbers and bingo_claims used `FOR ALL
-- USING(true) WITH CHECK(true)`, so any client holding the public anon key could
-- mutate marked cells, call numbers, and insert winning claims directly,
-- bypassing the game APIs (cheating/griefing).
--
-- After: anon may READ (realtime subscriptions need this) but cannot write. Every
-- write now goes through a server route using the service role, which bypasses RLS:
--   - /api/bingo/mark           — authorized by resume_token (assertPlayer)
--   - /api/bingo/claim          — authorized by resume_token (assertPlayer)
--   - /api/bingo/call           — host-authorized (host_token)
--   - /api/bingo/settings       — host-authorized (host_token)
--   - /api/bingo/sync           — system/auto-call, only acts past the interval
--   - /api/games/[code]/start      — host-authorized (creates bingo cards)
--   - /api/games/[code]/play-again — host-authorized (clear)
--   - /api/players (DELETE)        — host- or player-session authorized (remove)
--   - /api/players/promote         — promotes a viewer (creates a bingo card)
--
-- See docs/rls-hardening.md for the full plan and rollout sequence.

alter table bingo_cards enable row level security;
drop policy if exists "public_bingo_cards" on bingo_cards;
drop policy if exists "bingo_cards_read" on bingo_cards;
create policy "bingo_cards_read" on bingo_cards for select using (true);

alter table bingo_called_numbers enable row level security;
drop policy if exists "public_bingo_called_numbers" on bingo_called_numbers;
drop policy if exists "bingo_called_numbers_read" on bingo_called_numbers;
create policy "bingo_called_numbers_read" on bingo_called_numbers for select using (true);

alter table bingo_claims enable row level security;
drop policy if exists "public_bingo_claims" on bingo_claims;
drop policy if exists "bingo_claims_read" on bingo_claims;
create policy "bingo_claims_read" on bingo_claims for select using (true);

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted — restores the permissive policy if a regression appears).
-- Apply as a new forward migration; do NOT edit this file after it has shipped.
--
-- drop policy if exists "bingo_cards_read" on bingo_cards;
-- create policy "public_bingo_cards" on bingo_cards
--   for all using (true) with check (true);
--
-- drop policy if exists "bingo_called_numbers_read" on bingo_called_numbers;
-- create policy "public_bingo_called_numbers" on bingo_called_numbers
--   for all using (true) with check (true);
--
-- drop policy if exists "bingo_claims_read" on bingo_claims;
-- create policy "public_bingo_claims" on bingo_claims
--   for all using (true) with check (true);
-- ----------------------------------------------------------------------------
