-- RLS lockdown: I Call On / NPAT (Name-Place-Animal-Thing) — server-authoritative write model.
--
-- Before: npat_answers and npat_marks used `FOR ALL USING(true) WITH CHECK(true)`,
-- so any client holding the public anon key could write answers, flip mark
-- validity, or overwrite another player's submission directly, bypassing the
-- game APIs (cheating/griefing).
--
-- After: anon may READ (realtime subscriptions need this) but cannot write. Every
-- write now goes through a server route using the service role, which bypasses RLS:
--   - /api/npat/submit         — authorized by resume_token (assertPlayer)
--   - /api/npat/draft          — authorized by resume_token (assertPlayer)
--   - /api/npat/mark           — authorized by resume_token (assertPlayer)
--   - /api/npat/dispute        — authorized by resume_token (assertPlayer)
--   - /api/npat/letter         — authorized by resume_token (assertPlayer; caller-only)
--   - /api/npat/caller-approve — authorized by resume_token (assertPlayer; caller-only)
--   - /api/npat/advance        — system/timer, only acts when a phase deadline has passed
--   - /api/games/[code]/start      — host-authorized (initialize)
--   - /api/games/[code]/play-again — host-authorized (clear)
--   - /api/players (DELETE)        — host- or player-session authorized (remove)
--
-- See docs/rls-hardening.md for the full plan and rollout sequence.

alter table npat_answers enable row level security;
drop policy if exists "public_npat_answers" on npat_answers;
drop policy if exists "npat_answers_read" on npat_answers;
create policy "npat_answers_read" on npat_answers for select using (true);

alter table npat_marks enable row level security;
drop policy if exists "public_npat_marks" on npat_marks;
drop policy if exists "npat_marks_read" on npat_marks;
create policy "npat_marks_read" on npat_marks for select using (true);

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted — restores the permissive policy if a regression appears).
-- Apply as a new forward migration; do NOT edit this file after it has shipped.
--
-- drop policy if exists "npat_answers_read" on npat_answers;
-- create policy "public_npat_answers" on npat_answers
--   for all using (true) with check (true);
--
-- drop policy if exists "npat_marks_read" on npat_marks;
-- create policy "public_npat_marks" on npat_marks
--   for all using (true) with check (true);
-- ----------------------------------------------------------------------------
