-- Phase 3: stop exposing the secret auth tokens to the public roles.
--
-- `games.host_token` and `players.resume_token` are the credentials the app uses to
-- authorize host/player actions. They were readable by anyone with the anon key
-- (via REST `select` AND via realtime change payloads, since both tables are in the
-- realtime publication), which let an attacker read a token and impersonate a
-- host/player through the now token-gated APIs.
--
-- Fix: revoke the public roles' table-wide SELECT and re-grant SELECT on every column
-- EXCEPT the secret token. The service role bypasses these grants, so all server-side
-- auth reads keep working. Realtime payloads for the anon role exclude columns it can't
-- select, so the tokens stop leaking over realtime too (verify on the live DB).
--
-- The grants are built dynamically from information_schema so we don't hand-enumerate the
-- (large, frequently-extended) column lists.
--
-- ⚠️ FUTURE SCHEMA CHANGES: anon/authenticated now hold COLUMN-level (not table-level)
-- SELECT on games/players. Any NEW column added to these tables must also be granted to
-- anon/authenticated (re-running this block does that), or client reads of the new column
-- will error. This fails closed (a read error, never a token leak).

do $$
declare
  game_cols text;
  player_cols text;
  role_name text;
begin
  select string_agg(quote_ident(column_name), ', ')
    into game_cols
    from information_schema.columns
   where table_schema = 'public' and table_name = 'games' and column_name <> 'host_token';

  select string_agg(quote_ident(column_name), ', ')
    into player_cols
    from information_schema.columns
   where table_schema = 'public' and table_name = 'players' and column_name <> 'resume_token';

  foreach role_name in array array['anon', 'authenticated'] loop
    execute format('revoke select on public.games from %I', role_name);
    execute format('grant select (%s) on public.games to %I', game_cols, role_name);
    execute format('revoke select on public.players from %I', role_name);
    execute format('grant select (%s) on public.players to %I', player_cols, role_name);
  end loop;
end $$;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted — restores full table-level read for the public roles).
-- Apply as a new forward migration; do NOT edit this file after it has shipped.
--
-- grant select on public.games to anon, authenticated;
-- grant select on public.players to anon, authenticated;
-- ----------------------------------------------------------------------------
