-- Phase 5 RLS lockdown: core gameplay tables.
--
-- These tables back the 14 game types with no dedicated tables (the voting games,
-- who-said-this, hot-seat, custom) plus shared infra used by every game. Until now they
-- used permissive `FOR ALL USING(true) WITH CHECK(true)` policies, so anyone with the anon
-- key could write them directly. All writers are now server-side (service role) with
-- host/player(resume_token) authorization, so we lock anon to SELECT-only.
--
-- Anon SELECT stays open (public lobby, join-by-code, realtime subscriptions). The service
-- role bypasses RLS, so server writes continue to work. For `games`/`players`, column-level
-- grants from migration 0122 additionally keep host_token/resume_token unreadable.
--
-- Implemented as a dynamic block: drop EVERY existing policy on each table, then create a
-- single SELECT-only `<table>_read` policy — guaranteeing no write policy survives.

do $$
declare
  pol record;
  tbl text;
  tables text[] := array[
    'games', 'players', 'participants', 'rounds', 'votes', 'confessions',
    'player_questions', 'wst_quote_pool', 'anime_quote_pool', 'hot_seat_submissions',
    'game_snapshots'
  ];
begin
  foreach tbl in array tables loop
    execute format('alter table public.%I enable row level security', tbl);
    for pol in select policyname from pg_policies where schemaname = 'public' and tablename = tbl loop
      execute format('drop policy %I on public.%I', pol.policyname, tbl);
    end loop;
    execute format('create policy %I on public.%I for select using (true)', tbl || '_read', tbl);
  end loop;
end $$;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted — restores permissive write access for anon). Apply as a new forward
-- migration; do NOT edit this file after it has shipped.
--
-- do $$
-- declare tbl text;
--   tables text[] := array['games','players','participants','rounds','votes','confessions',
--     'player_questions','wst_quote_pool','anime_quote_pool','hot_seat_submissions','game_snapshots'];
-- begin
--   foreach tbl in array tables loop
--     execute format('drop policy if exists %I on public.%I', tbl || '_read', tbl);
--     execute format('create policy %I on public.%I for all using (true) with check (true)', tbl || '_all', tbl);
--   end loop;
-- end $$;
-- ----------------------------------------------------------------------------
